apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    createdAt: "2024-05-15T02:34:14Z"
    operators.operatorframework.io/builder: operator-sdk-v1.34.1
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: harness-gitops-agent-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Deploy and Manage the Harness GitOps Agent
  displayName: harness-gitops-agent
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: []
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - harness
  - git-ops
  - gitops
  - agent
  links:
  - name: Harness Gitops Agent Operator
    url: https://harness-gitops-agent-operator.domain
  maturity: alpha
  provider:
    name: Derek
    url: redhat.com
  version: 0.0.1
