apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: harness-gitops-agent-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Deploy and Manage the Harness GitOps Agent
  displayName: harness-gitops-agent
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - harness
  - git-ops
  - gitops
  - agent
  links:
  - name: Harness Gitops Agent Operator
    url: https://harness-gitops-agent-operator.domain
  maturity: alpha
  provider:
    name: Derek
    url: redhat.com
  version: 0.0.0
